// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftreserveTracker.Web.Data;

#nullable disable

namespace SoftreserveTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.LootAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwardedToRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisenchanted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaidSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftReserveWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoftresId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaidSessionId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("LootAwards");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.LootRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("LootAwardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlusOneState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RollAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RolledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LootAwardId", "PlayerId");

                    b.ToTable("LootRolls");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RosterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RosterId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.PlusOneBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlusOneBalances");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaidType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaidWeekId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftresId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaidWeekId", "RaidType", "SessionDate", "SoftresId");

                    b.ToTable("RaidSessions");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RosterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RosterId", "PeriodStart")
                        .IsUnique();

                    b.HasIndex("RosterId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("RaidWeeks");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.Roster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.SessionReservationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwardedToPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ItemDropped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlusOneDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaidSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwardedToPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaidSessionId", "PlayerId", "ItemId");

                    b.ToTable("SessionReservationResults");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.SoftReserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BossSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerClass")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaidSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spec")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaidSessionId", "PlayerId", "ItemId");

                    b.ToTable("SoftReserves");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RaidSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaidSessionId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.LootAward", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.RaidSession", "RaidSession")
                        .WithMany("LootAwards")
                        .HasForeignKey("RaidSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "WinnerPlayer")
                        .WithMany("LootAwards")
                        .HasForeignKey("WinnerPlayerId");

                    b.Navigation("RaidSession");

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.LootRoll", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.LootAward", "LootAward")
                        .WithMany("Rolls")
                        .HasForeignKey("LootAwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "Player")
                        .WithMany("LootRolls")
                        .HasForeignKey("PlayerId");

                    b.Navigation("LootAward");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.Player", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Roster", "Roster")
                        .WithMany("Players")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.PlusOneBalance", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "Player")
                        .WithMany("PlusOneBalances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidSession", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.RaidWeek", "RaidWeek")
                        .WithMany("Sessions")
                        .HasForeignKey("RaidWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaidWeek");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidWeek", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Roster", "Roster")
                        .WithMany("RaidWeeks")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.SessionReservationResult", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "AwardedToPlayer")
                        .WithMany()
                        .HasForeignKey("AwardedToPlayerId");

                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "Player")
                        .WithMany("ReservationResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftreserveTracker.Web.Models.Entities.RaidSession", "RaidSession")
                        .WithMany("ReservationResults")
                        .HasForeignKey("RaidSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardedToPlayer");

                    b.Navigation("Player");

                    b.Navigation("RaidSession");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.SoftReserve", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.Player", "Player")
                        .WithMany("SoftReserves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftreserveTracker.Web.Models.Entities.RaidSession", "RaidSession")
                        .WithMany("SoftReserves")
                        .HasForeignKey("RaidSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("RaidSession");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.UploadedFile", b =>
                {
                    b.HasOne("SoftreserveTracker.Web.Models.Entities.RaidSession", "RaidSession")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("RaidSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaidSession");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.LootAward", b =>
                {
                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.Player", b =>
                {
                    b.Navigation("LootAwards");

                    b.Navigation("LootRolls");

                    b.Navigation("PlusOneBalances");

                    b.Navigation("ReservationResults");

                    b.Navigation("SoftReserves");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidSession", b =>
                {
                    b.Navigation("LootAwards");

                    b.Navigation("ReservationResults");

                    b.Navigation("SoftReserves");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.RaidWeek", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SoftreserveTracker.Web.Models.Entities.Roster", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("RaidWeeks");
                });
#pragma warning restore 612, 618
        }
    }
}
